apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
#  namespace: argocd # external-developers-projectには権限ない
spec:
  project: external-developers-project
  source:
    repoURL: https://github.com/4nm1tsu/sample-app
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: external-developers
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
