apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nginx-app-secrets
  namespace: external-developers
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: openbao-store
    kind: SecretStore
  target:
    name: simple-nginx-secret
  data:
    - secretKey: api_key
      remoteRef:
        key: sample-app
        property: API_TOKEN
