apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nginx-app-secrets
  namespace: external-developers
spec:
  refreshInterval: "1h" # 同期頻度
  secretStoreRef:
    name: openbao-store
    kind: SecretStore
  target:
    name: simple-nginx-secret
  data:
    - secretKey: api_key # アプリ側で使いたいキー名
      remoteRef:
        key: external-developers/data/sample-app # OpenBao上のパス
        property: API_TOKEN # OpenBao上のJSONキー名
