apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-nginx-ingress
  namespace: external-developer-ns
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer # 証明書自動更新
    nginx.ingress.kubernetes.io/ssl-redirect: "true" # httpsリダイレクト
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - nginx.4nm1tsu.com
      secretName: letsencrypt-cert-nginx # 証明書作成
  rules:
  - host: nginx.4nm1tsu.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simple-nginx-svc
            port:
              number: 80
