apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nginx
  namespace: external-developer-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-nginx
  template:
    metadata:
      labels:
        app: simple-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: simple-nginx-svc
  namespace: external-developer-ns
spec:
  selector:
    app: simple-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
