apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: external-developers
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi 
  storageClassName: external-developers-nfs
